# -*- coding: utf-8 -*-
"""Hand-written Arabic for empty/fuzzy django.po entries."""

TRANSLATIONS: dict[str, str] = {
    "(copy)": "(نسخة)",
    " (copy)": " (نسخة)",
    "%%(shown)s shown · %%(total)s total matches": "معروض %%(shown)s · إجمالي التطابقات %%(total)s",
    "(studio — sign-in required)": "(الاستوديو — يتطلب تسجيل الدخول)",
    "A PDF preview is not available (LibreOffice is not installed on the server). Use a download button below if shown.": "معاينة PDF غير متاحة (LibreOffice غير مثبت على الخادم). استخدم زر التنزيل أدناه إن وُجد.",
    "A related link for this form and step already exists.": "رابط مرتبط لهذا النموذج والخطوة موجود بالفعل.",
    "A secure share link is already enabled.": "رابط مشاركة آمن مفعّل بالفعل.",
    "API secret for the header above. Leave blank when editing to keep the current secret.": "سر API للترويسة أعلاه. اتركه فارغًا عند التحرير للاحتفاظ بالسر الحالي.",
    "Access denied": "تم رفض الوصول",
    "Add at least one checklist item (one per line).": "أضف عنصرًا واحدًا على الأقل في القائمة (سطر لكل عنصر).",
    "Add at least one field to preview this form. The preview matches the live layout once fields exist.": "أضف حقلًا واحدًا على الأقل لمعاينة هذا النموذج. تطابق المعاينة التخطيط الحي بعد إضافة الحقول.",
    "Anonymous (not signed in; no email stored)": "مجهول (غير مسجّل الدخول؛ لا بريد محفوظ)",
    "Anonymous — no account or email was stored.": "مجهول — لم يُحفظ حساب ولا بريد.",
    "Another logo already uses this position. Edit that logo or pick a different slot.": "شعار آخر يستخدم هذا الموضع. عدّل ذلك الشعار أو اختر موضعًا آخر.",
    "Any state": "أي حالة",
    "Applicant (email)": "المقدّم (البريد)",
    "Applicant link (token)": "رابط المقدّم (رمز)",
    "Applicant only": "للمقدّم فقط",
    "Applicant view": "عرض المقدّم",
    "Approval did not complete. Refresh the page and try again.": "لم يكتمل الاعتماد. حدّث الصفحة وحاول مجددًا.",
    "Approval undone (within %(minutes)d minutes). Workflow position reverted.": "تم التراجع عن الاعتماد (خلال %(minutes)d دقيقة). أُعيدت خطوة سير العمل.",
    "Approval undone. The timeline records this change.": "تم التراجع عن الاعتماد. يُسجّل الخط الزمني هذا التغيير.",
    "Archived forms cannot be duplicated. Restore the form first, then duplicate it.": "لا يمكن نسخ النماذج المؤرشفة. أعد النموذج أولًا ثم انسخه.",
    "Ask a superuser to configure organization SMTP and From address before automatic emails can be sent.": "اطلب من المشرف الأعلى ضبط SMTP وعنوان المرسل للمنظمة قبل إرسال البريد التلقائي.",
    "Automatic emails use the templates below and your organization SMTP. They are only sent when notifications and email are enabled for the organization.": "يستخدم البريد التلقائي القوالب أدناه وSMTP المنظمة. يُرسل فقط عند تفعيل الإشعارات والبريد للمنظمة.",
    "Behavior and helper text on the live form.": "السلوك والنص المساعد في النموذج الحي.",
    "Block submit when another response on this form already used the same answer (e.g. ID number or email). Applies to text-like, number, and date fields.": "منع الإرسال إذا استُخدمت نفس الإجابة في رد آخر على هذا النموذج (مثل رقم الهوية أو البريد). ينطبق على حقول النص والرقم والتاريخ.",
    "Body": "المحتوى",
    "By": "بواسطة",
    "Cannot undo this approval (missing previous step).": "لا يمكن التراجع عن هذا الاعتماد (الخطوة السابقة مفقودة).",
    "Caps length on the public form. Empty = defaults (short text/email/paragraph).": "يحدّ الطول في النموذج العام. فارغ = الافتراضي (نص قصير/بريد/فقرة).",
    "Case-insensitive substring that must appear.": "جزء نصي يجب أن يظهر (بلا تمييز حالة الأحرف).",
    "Case-insensitive substring that must not appear.": "جزء نصي يجب ألا يظهر (بلا تمييز حالة الأحرف).",
    "Center (above title)": "وسط (فوق العنوان)",
    "Choose either STARTTLS or SSL, not both.": "اختر STARTTLS أو SSL، وليس كليهما.",
    "Conditional visibility": "إظهار مشروط",
    "Configure SMTP and From address under organization settings before automatic emails can be sent.": "اضبط SMTP وعنوان المرسل في إعدادات المنظمة قبل إرسال البريد التلقائي.",
    "Configure three color sets. Only the active one is used on the public portal; the others stay saved until you switch.": "اضبط ثلاث مجموعات ألوان. تُستخدم النشطة فقط في البوابة العامة؛ تبقى الأخرى محفوظة حتى التبديل.",
    "Could not run the inbox assistant. Try again.": "تعذّر تشغيل مساعد صندوق الوارد. حاول مجددًا.",
    "Could not send the email. Check organization email settings (SMTP host, port, TLS/SSL, credentials) and try again.": "تعذّر إرسال البريد. راجع إعدادات بريد المنظمة (مضيف SMTP، المنفذ، TLS/SSL، بيانات الاعتماد) وحاول مجددًا.",
    "Date & time": "التاريخ والوقت",
    "Date must be on or after %(d)s.": "يجب أن يكون التاريخ في %(d)s أو بعده.",
    "Date must be on or before %(d)s.": "يجب أن يكون التاريخ في %(d)s أو قبله.",
    "Details": "التفاصيل",
    "Directory sign-in failed: your organization’s API did not return success, or the response was invalid. The endpoint must answer with HTTP 200 and JSON containing \"success\": true (when present) and an \"employee\" or \"user\" object (e.g. username, email, employee_number). When directory login is enabled for this organization, the studio does not fall back to the Django password.": "فشل تسجيل الدخول عبر الدليل: لم تُرجع واجهة المنظمة نجاحًا أو كان الرد غير صالح. يجب أن يُجيب المسار بـ HTTP 200 وJSON يحتوي \"success\": true (إن وُجد) وكائن \"employee\" أو \"user\" (مثل username وemail وemployee_number). عند تفعيل دليل الدخول للمنظمة، لا يعود الاستوديو لكلمة مرور Django.",
    "Directory sign-in uses your organization username (<code>entity-slug-username</code>, e.g. <code>mosa-kuwait-jdoe</code>) and password. If directory sign-in fails, access is not granted (no studio password fallback).": "يستخدم تسجيل الدخول عبر الدليل اسم المستخدم في المنظمة (<code>entity-slug-username</code>، مثل <code>mosa-kuwait-jdoe</code>) وكلمة المرور. عند الفشل لا يُمنح الوصول (لا بديل بكلمة مرور الاستوديو).",
    "Discussion thread": "سلسلة النقاش",
    "Download ODT for editing": "تنزيل ODT للتحرير",
    "Duplicate": "نسخ",
    "Earliest allowed date (inclusive).": "أبكر تاريخ مسموح (شامل).",
    "Email applicant": "مراسلة المقدّم",
    "Email is turned off for this organization. A superuser can enable it under Organizations → Settings → Email notifications.": "البريد معطّل لهذه المنظمة. يمكن للمشرف الأعلى تفعيله من المنظمات → الإعدادات → إشعارات البريد.",
    "Email notification templates saved.": "تم حفظ قوالب إشعارات البريد.",
    "Email notifications": "إشعارات البريد",
    "Email sent to %(addr)s.": "أُرسل البريد إلى %(addr)s.",
    "Email sent to applicant (%(addr)s): %(subject)s": "أُرسل البريد للمقدّم (%(addr)s): %(subject)s",
    "Enter a message before posting.": "أدخل رسالة قبل النشر.",
    "Enter a number greater than or equal to %(n)s.": "أدخل رقمًا أكبر من أو يساوي %(n)s.",
    "Enter a number less than or equal to %(n)s.": "أدخل رقمًا أصغر من أو يساوي %(n)s.",
    "Enter a reason for rejection before submitting.": "أدخل سبب الرفض قبل الإرسال.",
    "Enter a whole number (no decimals).": "أدخل عددًا صحيحًا (بدون كسور).",
    "Enter a whole-number tenant ID.": "أدخل معرّف مستأجر (tenant) عددًا صحيحًا.",
    "Enter at least %(n)d characters.": "أدخل %(n)d حرفًا على الأقل.",
    "Enter at most %(n)d characters.": "أدخل %(n)d حرفًا كحد أقصى.",
    "Enter the applicant’s email address (no email field or address found on this submission).": "أدخل بريد المقدّم (لا حقل بريد ولا عنوان في هذا التقديم).",
    "Enter your organization username (e.g. mosa-kuwait-jdoe).": "أدخل اسم مستخدم المنظمة (مثل mosa-kuwait-jdoe).",
    "Event": "حدث",
    "Exact required value": "القيمة المطلوبة بالضبط",
    "Exact tag (your private labels)": "وسم دقيق (تسمياتك الخاصة)",
    "Extra checks on submissions. Applies by field type as described below; leave blank to skip.": "فحوصات إضافية على التقديمات. حسب نوع الحقل كما هو موضّح؛ اتركه فارغًا للتخطي.",
    "Field duplicated. You can adjust the internal name and label if needed.": "تم نسخ الحقل. يمكنك تعديل الاسم الداخلي والتسمية عند الحاجة.",
    "For radio buttons and checklist: show each choice in a horizontal row or a vertical column.": "لأزرار الاختيار والقائمة: اعرض كل خيار في صف أفقي أو عمود رأسي.",
    "Forbidden substring": "جزء نصي ممنوع",
    "Form duplicated. The copy is a draft; review settings and publishing when you are ready.": "تم نسخ النموذج. النسخة مسودة؛ راجع الإعدادات والنشر عند الجاهزية.",
    "Forward": "إحالة",
    "Forward to": "إحالة إلى",
    "Forwarding is enabled for this form, but only when you submitted while signed in. Anonymous submissions cannot use this option.": "الإحالة مفعّلة لهذا النموذج، لكن فقط إذا أرسلت وأنت مسجّل الدخول. لا يمكن للتقديمات المجهولة استخدامها.",
    "Forwarding is not enabled for this form.": "الإحالة غير مفعّلة لهذا النموذج.",
    "Full URL (http:// or https://; prefer HTTPS in production) that accepts POST JSON {\"tenant_id\", \"username\", \"password\"} and returns HTTP 200 with JSON {\"success\": true, \"user\": { … }}. Typical user fields include samAccountName, userPrincipalName, displayName, givenName, surname, emailAddress, employeeId, department, title, office, telephoneNumber, and enabled.": "عنوان URL كامل (http:// أو https://؛ يُفضّل HTTPS في الإنتاج) يقبل POST JSON {\"tenant_id\", \"username\", \"password\"} ويُرجع HTTP 200 مع JSON {\"success\": true, \"user\": { … }}. حقول المستخدم الشائعة: samAccountName وuserPrincipalName وdisplayName وغيرها.",
    "Go to main site": "الانتقال إلى الموقع الرئيسي",
    "HTTP header for the secret below. Blank or Authorization uses Bearer; any other name sends the raw token.": "ترويسة HTTP للسر أدناه. فارغ أو Authorization يستخدم Bearer؛ أي اسم آخر يرسل الرمز كما هو.",
    "Header name is too long (max 64 characters).": "اسم الترويسة طويل جدًا (64 حرفًا كحد أقصى).",
    "Hello,\n\nRegarding your submission to {{form_title}} (reference {{reference}}).\n\n(Add your message here before sending.)\n\nThank you.": "مرحبًا،\n\nبخصوص تقديمك إلى {{form_title}} (المرجع {{reference}}).\n\n(أضف رسالتك هنا قبل الإرسال.)\n\nشكرًا لك.",
    "Hello,\n\nWe received your submission.\n\nReference: {{reference}}\nForm: {{form_title}}\nOrganization: {{entity_name}}\n\nYou can follow progress here:\n{{track_url}}\n\nThank you.": "مرحبًا،\n\nاستلمنا تقديمك.\n\nالمرجع: {{reference}}\nالنموذج: {{form_title}}\nالمنظمة: {{entity_name}}\n\nيمكنك متابعة التقدم هنا:\n{{track_url}}\n\nشكرًا لك.",
    "Hello,\n\nYour submission has been accepted and the workflow is complete.\n\nReference: {{reference}}\nForm: {{form_title}}\n\nView details:\n{{track_url}}\n\nThank you.": "مرحبًا،\n\nقُبل تقديمك واكتمل سير العمل.\n\nالمرجع: {{reference}}\nالنموذج: {{form_title}}\n\nعرض التفاصيل:\n{{track_url}}\n\nشكرًا لك.",
    "Hello,\n\nYour submission was not approved.\n\nReference: {{reference}}\nForm: {{form_title}}\nReason: {{decision_comment}}\n\nView details:\n{{track_url}}\n\nThank you.": "مرحبًا،\n\nلم يُعتمد تقديمك.\n\nالمرجع: {{reference}}\nالنموذج: {{form_title}}\nالسبب: {{decision_comment}}\n\nعرض التفاصيل:\n{{track_url}}\n\nشكرًا لك.",
    "If set, the answer must equal this exact string (after trimming). Rare; use sparingly.": "إن وُضع، يجب أن تساوي الإجابة هذا النص بالضبط (بعد القص). نادر؛ استخدمه بحذر.",
    "Inbox assistant": "مساعد صندوق الوارد",
    "Include your organization slug before your username (e.g. %(examples)s).": "ضمّن معرّف المنظمة قبل اسم المستخدم (مثل %(examples)s).",
    "Integer tenant_id sent with every directory login request for this organization (not shown on the sign-in page).": "معرّف tenant_id عدد صحيح يُرسل مع كل طلب دليل دخول لهذه المنظمة (لا يظهر في صفحة الدخول).",
    "Invalid regular expression: %(err)s": "تعبير نمطي غير صالح: %(err)s",
    "Invalid workflow action. Refresh the page and try again.": "إجراء سير عمل غير صالح. حدّث الصفحة وحاول مجددًا.",
    "Latest allowed date (inclusive).": "آخر تاريخ مسموح (شامل).",
    "Left (beside title column)": "يسار (بجانب عمود العنوان)",
    "Left and right sit beside the title column; center appears above the form title.": "اليسار واليمين بجانب عمود العنوان؛ الوسط فوق عنوان النموذج.",
    "Loading": "جارٍ التحميل",
    "Login API": "واجهة تسجيل الدخول",
    "Max length must be greater than or equal to min length.": "يجب أن يكون الحد الأقصى للطول ≥ الحد الأدنى.",
    "Max number": "الحد الأقصى للرقم",
    "Maximum must be greater than or equal to minimum.": "يجب أن يكون الحد الأقصى ≥ الحد الأدنى.",
    "Maximum numeric value (inclusive).": "أقصى قيمة رقمية (شامل).",
    "Merged DOCX requires a .docx file in the primary print template field.": "يتطلب DOCX المدمج ملف .docx في حقل قالب الطباعة الأساسي.",
    "Message about your submission {{reference}}": "رسالة بخصوص تقديمك {{reference}}",
    "Message is too long (%(n)d characters maximum).": "الرسالة طويلة جدًا (%(n)d حرفًا كحد أقصى).",
    "Message posted.": "نُشرت الرسالة.",
    "Min number": "الحد الأدنى للرقم",
    "Minimum numeric value (inclusive).": "أدنى قيمة رقمية (شامل).",
    "New thread message": "رسالة جديدة في السلسلة",
    "No connected submissions matched that question. Try different keywords or filters.": "لا تقديمات مرتبطة تطابق هذا السؤال. جرّب كلمات أو مرشحات أخرى.",
    "No open forms right now. Check back later.": "لا نماذج مفتوحة الآن. عُد لاحقًا.",
    "Notes and questions for everyone who can open this submission in the studio—assignees on any step, delegates, and others with access through the inbox or submission search.": "ملاحظات وأسئلة لكل من يمكنه فتح هذا التقديم في الاستوديو—المكلفون في أي خطوة والمفوّضون ومن لهم وصول عبر صندوق الوارد أو البحث.",
    "Notifications are disabled for this organization. Enable notifications and email settings under Organizations → Settings.": "الإشعارات معطّلة لهذه المنظمة. فعّل الإشعارات وإعدادات البريد من المنظمات → الإعدادات.",
    "Numbers only: reject values with a decimal point.": "أرقام فقط: رفض القيم التي تحتوي فاصلة عشرية.",
    "Only people who can open the studio see this page. Scanning opens the public form link used for submissions.": "يرى هذه الصفحة من يفتح الاستوديو فقط. المسح يفتح رابط النموذج العام للتقديمات.",
    "Only you can see this. It is not shared with assignees or on the timeline.": "أنت فقط من يرى هذا. لا يُشارك مع المكلفين ولا على الخط الزمني.",
    "Only you see these labels. Separate tags with commas or new lines. On the Search page, use the “Your tag” field to list submissions you marked the same way.": "أنت فقط ترى هذه التسميات. افصل الوسوم بفواصل أو أسطر. في البحث استخدم حقل «وسمك» لعرض ما علّمته بنفس الطريقة.",
    "Open in mail app": "فتح في تطبيق البريد",
    "Optional directory login API. When active, studio sign-in uses the tenant ID from settings plus the username and password entered on this page—if the API does not return success, sign-in is denied (no Django password fallback).": "واجهة دليل دخول اختيارية. عند التفعيل يستخدم الاستوديو tenant_id من الإعدادات مع اسم المستخدم وكلمة المرور—عند الفشل يُرفض الدخول (لا بديل Django).",
    "Optional image for the studio banner, public portal, and mobile app when users belong to this organization only. For PNG, JPEG, and WebP, very light backgrounds are removed on upload (saved as PNG). SVG and GIF are unchanged.": "صورة اختيارية لشعار الاستوديو والبوابة والتطبيق عند انتماء المستخدمين لهذه المنظمة فقط. لـ PNG وJPEG وWebP تُزال الخلفيات الفاتحة جدًا عند الرفع (تُحفظ PNG). SVG وGIF دون تغيير.",
    "Optional when approving; required when rejecting.": "اختياري عند الاعتماد؛ مطلوب عند الرفض.",
    "Organization created. %(n)d sample starter forms were added.": "تم إنشاء المنظمة. أُضيف %(n)d نموذجًا تجريبيًا.",
    "Outgoing sender. Use a display name plus address, or email only.": "المرسل الصادر. اسم عرض مع عنوان، أو بريد فقط.",
    "PDF needs a DOCX or PDF in the primary template field, or an ODT in the optional ODT field.": "يتطلب PDF ملف DOCX أو PDF في القالب الأساسي، أو ODT في الحقل الاختياري.",
    "PDF preview is not available for this file.": "معاينة PDF غير متاحة لهذا الملف.",
    "PNG, JPEG, GIF, WebP, or SVG. Maximum three logos per form (one per position). For PNG, JPEG, and WebP, very light backgrounds are removed on upload (saved as PNG).": "PNG أو JPEG أو GIF أو WebP أو SVG. ثلاثة شعارات كحد أقصى لكل نموذج (واحد لكل موضع). للصيغ المذكورة تُزال الخلفيات الفاتحة جدًا عند الرفع.",
    "PNG, JPEG, GIF, WebP, or SVG. You can add many signatures per user. For PNG, JPEG, and WebP, very light backgrounds are removed automatically (stored as PNG). SVG and GIF are not altered.": "PNG أو JPEG أو GIF أو WebP أو SVG. يمكن إضافة توقيعات متعددة لكل مستخدم. للصيغ المذكورة تُزال الخلفيات الفاتحة تلقائيًا. SVG وGIF دون تغيير.",
    "Placeholders in subject and body (plain text):": "عناصر نائبة في الموضوع والمحتوى (نص عادي):",
    "Please correct the errors below.": "صحّح الأخطاء أدناه.",
    "Position in header": "الموضع في الترويسة",
    "Post message": "نشر رسالة",
    "Prefill manual “Email applicant” with staff contact template": "ملء «مراسلة المقدّم» يدويًا بقالب اتصال الموظفين",
    "Preview mode": "وضع المعاينة",
    "Primary signature updated.": "تم تحديث التوقيع الأساسي.",
    "Private note": "ملاحظة خاصة",
    "Publish the form before sharing the public link; draft forms cannot be opened or submitted by respondents.": "انشر النموذج قبل مشاركة الرابط العام؛ لا يمكن للمستجيبين فتح المسودات أو إرسالها.",
    "Python regular expression tested against the full string (search).": "تعبير نمطي Python يُختبر على النص الكامل (بحث).",
    "QR code for this form": "رمز QR لهذا النموذج",
    "QR code generation is not available. Install the %(pkg)s package on the server.": "إنشاء QR غير متاح. ثبّت الحزمة %(pkg)s على الخادم.",
    "Record that this submission was brought to someone else’s attention (same organization). This adds an entry on the timeline below; it does not change workflow or send email automatically.": "سجّل أن هذا التقديم أُحيل لانتباه شخص آخر (نفس المنظمة). يُضاف إدخال على الخط الزمني؛ لا يغيّر سير العمل ولا يرسل بريدًا تلقائيًا.",
    "Record that this submission was brought to someone else’s attention. This adds a timeline entry and does not change workflow assignees or send email automatically.": "سجّل إحالة التقديم لانتباه آخر. يُضاف إدخال زمني دون تغيير المكلفين أو إرسال بريد تلقائي.",
    "Regarding your submission — %(form)s (%(ref)s)": "بخصوص تقديمك — %(form)s (%(ref)s)",
    "Regenerate secret (invalidate old QR)": "إعادة توليد السر (إبطال QR القديم)",
    "Regenerate the secret? Old QR codes and links with the previous secret will stop working.": "إعادة توليد السر؟ ستتوقف رموز QR والروابط بالسر القديم.",
    "Rejection reason": "سبب الرفض",
    'Related form available: "%(title)s". Complete it using the link in the related forms section below.': 'نموذج مرتبط متاح: «%(title)s». أكمله عبر الرابط في قسم النماذج المرتبطة أدناه.',
    "Related form is still a draft; publish it to enable the public applicant link.": "النموذج المرتبط ما زال مسودة؛ انشره لتفعيل رابط المقدّم العام.",
    'Related form submitted: "%(title)s".': 'تم تقديم النموذج المرتبط: «%(title)s».',
    "Reminders, follow-ups, personal context…": "تذكيرات، متابعات، سياق شخصي…",
    "Removing signature images is not available from this page. You can add images or set the primary; the user can remove their own on “My signatures”.": "إزالة صور التوقيع غير متاحة من هذه الصفحة. يمكنك الإضافة أو تعيين الأساسي؛ يزيل المستخدم توقيعه من «توقيعاتي».",
    "Requests": "الطلبات",
    "Right (beside title column)": "يمين (بجانب عمود العنوان)",
    "SMTP port must be between 1 and 65535.": "منفذ SMTP يجب أن يكون بين 1 و65535.",
    "Same organization; base workflow does not block on these.": "نفس المنظمة؛ سير العمل الأساسي لا ينتظرها.",
    "Search answers, field names, status, dates, categories, your tags, email, or reference — across every submission connected to you.": "ابحث في الإجابات وأسماء الحقول والحالة والتواريخ والفئات ووسومك والبريد والمرجع — في كل التقديمات المرتبطة بك.",
    "Search field answers, status, dates, tags, and more. Set OPENAI_API_KEY for smarter matching on field and form names.": "ابحث في إجابات الحقول والحالة والتواريخ والوسوم وغيرها. عيّن OPENAI_API_KEY لمطابقة أذكى لأسماء الحقول والنماذج.",
    "Search submissions you applied to or worked on": "ابحث في التقديمات التي قدّمتها أو عملت عليها",
    "Searching your connected submissions for matching keywords.": "جارٍ البحث في تقديماتك المرتبطة عن الكلمات المطابقة.",
    "Searching your inbox…": "جارٍ البحث في صندوق الوارد…",
    "Secondary accent": "لون ثانوي مميز",
    "Secure link & regenerate QR": "رابط آمن وإعادة توليد QR",
    "Secure share link is on. New QR codes and links include a secret; old links without it no longer open this form.": "رابط المشاركة الآمن مفعّل. رموز QR والروابط الجديدة تتضمن سرًا؛ الروابط القديمة بلا سر لا تفتح النموذج.",
    "Secure share link turned off. The public form URL works again without a secret query parameter.": "عُطّل رابط المشاركة الآمن. يعمل رابط النموذج العام مجددًا بلا معامل سر.",
    "Send a message through this organization's configured mail server. Replies go to your account email and the organization Reply-To when set.": "أرسل رسالة عبر خادم بريد المنظمة. تذهب الردود إلى بريد حسابك وReply-To للمنظمة إن وُضع.",
    "Send email on each intermediate approval step": "إرسال بريد عند كل خطوة اعتماد وسيطة",
    "Send email when a form is submitted": "إرسال بريد عند تقديم النموذج",
    "Send email when workflow is completed (accepted)": "إرسال بريد عند اكتمال سير العمل (قبول)",
    "Send email when workflow is rejected": "إرسال بريد عند رفض سير العمل",
    "Send question to inbox assistant": "إرسال السؤال لمساعد صندوق الوارد",
    "Set a From address in organization email settings.": "حدّد عنوان المرسل في إعدادات بريد المنظمة.",
    "Set a From address when email notifications are enabled.": "حدّد عنوان المرسل عند تفعيل إشعارات البريد.",
    "Set a valid SMTP port (1–65535) in organization email settings.": "حدّد منفذ SMTP صالحًا (1–65535) في إعدادات بريد المنظمة.",
    "Set an API secret when directory login is active.": "حدّد سر API عند تفعيل دليل الدخول.",
    "Set an SMTP host when email notifications are enabled.": "حدّد مضيف SMTP عند تفعيل إشعارات البريد.",
    "Set an SMTP password or clear the SMTP username in organization email settings.": "حدّد كلمة مرور SMTP أو امسح اسم مستخدم SMTP في إعدادات بريد المنظمة.",
    "Set an SMTP password when a username is provided.": "حدّد كلمة مرور SMTP عند إدخال اسم مستخدم.",
    "Set as primary": "تعيين كأساسي",
    "Set the directory API URL when directory login is active.": "حدّد عنوان واجهة الدليل عند تفعيل دليل الدخول.",
    "Set the tenant ID when directory login is active.": "حدّد معرّف المستأجر عند تفعيل دليل الدخول.",
    "Share secret rotated. Old QR codes, posters, and bookmarks with the previous link no longer work.": "تم تدوير سر المشاركة. رموز QR والملصقات والإشارات المرجعية بالرابط القديم لم تعد تعمل.",
    "Show this field only when another control field matches specific values.": "أظهر هذا الحقل فقط عندما يطابق حقل تحكم آخر قيمًا محددة.",
    "Showing %(lo)s–%(hi)s": "عرض %(lo)s–%(hi)s",
    "Showing the first %(n)s.": "عرض أول %(n)s.",
    "Sign in with the same account you used for the original submission, or open the related form link from your submission tracking page while using the same anonymous browser session.": "سجّل الدخول بنفس الحساب الذي استخدمته للتقديم الأصلي، أو افتح رابط النموذج المرتبط من صفحة التتبع بنفس جلسة المتصفح المجهولة.",
    "Sign in with the same account you used when you submitted to forward this submission to someone in the organization.": "سجّل الدخول بنفس الحساب الذي أرسلت به لإحالة هذا التقديم لشخص في المنظمة.",
    "Signed in when you submitted": "كنت مسجّل الدخول عند التقديم",
    "Starter sample forms pagination": "ترقيم النماذج التجريبية الأولية",
    "State": "الحالة",
    "Submission forwarded (timeline updated).": "تمت إحالة التقديم (حُدّث الخط الزمني).",
    "Submissions are disabled. This is how applicants will see the form.": "التقديمات معطّلة. هكذا يرى المقدّمون النموذج.",
    "Submissions connected to you: as <strong>applicant</strong> (account or matching email), on the <strong>current step</strong> as assignee or delegate, or anywhere on the <strong>workflow path</strong> (approvals, rejections, notes, forwards, attachments you added in manage). Use <strong>Your tag</strong> to narrow the list to submissions you labeled for yourself on the submission page.": "التقديمات المرتبطة بك: كـ<strong>مقدّم</strong> (حساب أو بريد مطابق)، في <strong>الخطوة الحالية</strong> كمكلّف أو مفوّض، أو في <strong>مسار سير العمل</strong>. استخدم <strong>وسمك</strong> لتضييق القائمة.",
    "Tenant ID must be at least 1.": "يجب أن يكون معرّف المستأجر 1 على الأقل.",
    "Text-like fields only. Empty = no minimum. Submitted text is trimmed before counting.": "حقول نصية فقط. فارغ = بلا حد أدنى. يُقص النص قبل العد.",
    "The From address is not a valid email address.": "عنوان المرسل ليس بريدًا إلكترونيًا صالحًا.",
    "The child form must belong to the same organization as this form.": "يجب أن ينتمي النموذج الفرعي لنفس منظمة هذا النموذج.",
    'The form “%(title)s” was archived. It no longer appears in public or normal studio lists.': 'أُرشف النموذج «%(title)s». لم يعد يظهر في القوائم العامة أو العادية للاستوديو.',
    'The form “%(title)s” was restored from archive.': 'أُعيد النموذج «%(title)s» من الأرشيف.',
    "Theme 1": "السمة 1",
    "Theme 2": "السمة 2",
    "Theme 3": "السمة 3",
    'There is no active organization registered for <code class="mf-code">%(slug)s</code> on this site. Check the address with your administrator, or open the main site below.': 'لا منظمة نشطة مسجّلة لـ<code class="mf-code">%(slug)s</code> على هذا الموقع. راجع العنوان مع المسؤول أو افتح الموقع الرئيسي أدناه.',
    "These are extra forms linked to submissions you started while signed in. Complete each one to finish your application.": "نماذج إضافية مرتبطة بتقديمات بدأتها وأنت مسجّل الدخول. أكمل كلًا لإنهاء طلبك.",
    "This approval can no longer be undone (deadline passed or submission changed).": "لم يعد بإمكان التراجع عن هذا الاعتماد (انتهت المهلة أو تغيّر التقديم).",
    'This field must contain “%(text)s”.': 'يجب أن يحتوي هذا الحقل على «%(text)s».',
    'This field must not contain “%(text)s”.': 'يجب ألا يحتوي هذا الحقل على «%(text)s».',
    "This form is archived — the link may not work for new submissions until it is restored and published.": "هذا النموذج مؤرشف — قد لا يعمل الرابط لتقديمات جديدة حتى الاستعادة والنشر.",
    "This form is not published yet — the link will show “not published” until you turn on Published in form settings.": "لم يُنشر هذا النموذج بعد — سيظهر «غير منشور» حتى تفعّل «منشور» في الإعدادات.",
    "This form is not published yet. If you manage it, open /manage/, edit the form, and turn on “Published” once you have at least one field and one workflow step.": "لم يُنشر بعد. إن كنت تديره، افتح /manage/ وفعّل «منشور» بعد وجود حقل وخطوة سير عمل واحدة على الأقل.",
    "This is a <strong>related form</strong> for your main submission <strong>%(title)s</strong> (reference …%(hex)s).": "هذا <strong>نموذج مرتبط</strong> لتقديمك الرئيسي <strong>%(title)s</strong> (مرجع …%(hex)s).",
    "This page is out of date. Refresh and try again.": "هذه الصفحة قديمة. حدّث وحاول مجددًا.",
    "This submission is closed. You cannot upload more documents here.": "هذا التقديم مغلق. لا يمكنك رفع مزيد من المستندات هنا.",
    "This submission was already updated—perhaps in another tab. Refresh the page.": "حُدّث هذا التقديم مسبقًا—ربما في تبويب آخر. حدّث الصفحة.",
    "This value does not match the required pattern.": "هذه القيمة لا تطابق النمط المطلوب.",
    "This value was already submitted on this form. Enter a different answer or contact the organization if you need help.": "أُرسلت هذه القيمة مسبقًا على هذا النموذج. أدخل إجابة مختلفة أو تواصل مع المنظمة.",
    "Thread": "السلسلة",
    "Thread messages": "رسائل السلسلة",
    "Title, slug, reference, email, username": "العنوان، المعرّف، المرجع، البريد، اسم المستخدم",
    "To": "إلى",
    "To is filled from %(src)s.": "يُملأ «إلى» من %(src)s.",
    "Turn off secure link": "إيقاف الرابط الآمن",
    "Turn off the secure link? The form will open without a secret in the URL again.": "إيقاف الرابط الآمن؟ سيفتح النموذج بلا سر في عنوان URL.",
    "Turn on a secure share link first, then you can rotate it.": "فعّل رابط مشاركة آمن أولًا، ثم يمكنك تدويره.",
    "Type, identifiers, and label shown to respondents.": "النوع والمعرّفات والتسمية المعروضة للمستجيبين.",
    "Unique value check applies to text, paragraph, email, dropdown, radio, number, and date fields only.": "فحص القيمة الفريدة ينطبق على حقول النص والفقرة والبريد والقائمة والراديو والرقم والتاريخ فقط.",
    "Unrecognized workflow action. Refresh the page and use Approve or Reject.": "إجراء سير عمل غير معروف. حدّث الصفحة واستخدم اعتماد أو رفض.",
    "Unsupported output format.": "صيغة إخراج غير مدعومة.",
    "Update on your submission to {{form_title}}": "تحديث بخصوص تقديمك إلى {{form_title}}",
    "Upload an ODT file in the optional ODT print template field to enable ODT download.": "ارفع ملف ODT في حقل قالب الطباعة الاختياري لتفعيل تنزيل ODT.",
    "Upload images of your signature for use in printable documents when you submit a form while signed in. You can add more than one (for example different languages or styles). The first image is used as the main signature in merged documents; use “Set as primary” to choose which image that is.": "ارفع صور توقيعك للمستندات القابلة للطباعة عند التقديم وأنت مسجّل الدخول. يمكنك إضافة أكثر من واحدة. الصورة الأولى تُستخدم أساسيًا؛ استخدم «تعيين كأساسي».",
    "Use STARTTLS (common on port 587).": "استخدم STARTTLS (شائع على المنفذ 587).",
    "Use a full URL starting with http:// or https://.": "استخدم عنوان URL كاملًا يبدأ بـ http:// أو https://.",
    "Use a valid HTTP header name (letters, digits, hyphen, and !#$&'*+.^_`|~).": "استخدم اسم ترويسة HTTP صالحًا.",
    'Use a valid address, e.g. "Team <mail@yourorg.com>".': 'استخدم عنوانًا صالحًا، مثل "الفريق <mail@yourorg.com>".',
    "Use implicit SSL (common on port 465). Disable STARTTLS when SSL is on.": "استخدم SSL ضمنيًا (شائع على 465). عطّل STARTTLS عند تفعيل SSL.",
    "View PDF": "عرض PDF",
    "View as PDF": "عرض كـ PDF",
    "View related answers": "عرض الإجابات المرتبطة",
    "Visitors see only the selected theme on the public portal. The other two are saved for later.": "يرى الزوار السمة المختارة فقط في البوابة العامة. تُحفظ السمتان الأخريان.",
    "Waiting for your response": "بانتظار ردك",
    "When a <strong>secure share link</strong> is on, the public URL must include a secret query parameter. The QR code and studio links include it. <strong>Regenerate</strong> replaces that secret so old printed QR codes and shared URLs stop working.": "عند تفعيل <strong>رابط مشاركة آمن</strong> يجب أن يتضمن عنوان URL العام معامل سر. رمز QR وروابط الاستوديو تتضمنه. <strong>إعادة التوليد</strong> يستبدل السر.",
    "When a submission reaches the chosen workflow step, the applicant can complete a linked form (same organization). The base workflow does not wait for it.": "عند وصول التقديم لخطوة مختارة يمكن للمقدّم إكمال نموذج مرتبط (نفس المنظمة). سير العمل الأساسي لا ينتظره.",
    "When enabled together with Notifications (under Theme & behavior), every outbound email for this organization—applicant mail from submissions and any future notification hooks—uses this SMTP server, not the global site mail settings in Django.": "عند التفعيل مع الإشعارات (ضمن السمة والسلوك) يستخدم كل بريد صادر لهذه المنظمة خادم SMTP هذا وليس إعدادات الموقع العامة.",
    "When enabled, studio sign-in for this organization uses only the directory API with the same username and password—no Django password fallback if the API rejects the credentials.": "عند التفعيل يستخدم تسجيل دخول الاستوديو واجهة الدليل فقط بنفس اسم المستخدم وكلمة المرور—بلا بديل Django عند الرفض.",
    "When on (and Notifications enabled), all system email for this organization uses the SMTP settings below.": "عند التفعيل (مع الإشعارات) يستخدم كل بريد النظام لهذه المنظمة إعدادات SMTP أدناه.",
    "When to send": "متى يُرسل",
    "Where this image appears in the live form header.": "أين تظهر هذه الصورة في ترويسة النموذج الحي.",
    "Workflow only (assignee or timeline)": "سير العمل فقط (مكلّف أو خط زمني)",
    "Write your message to the applicant…": "اكتب رسالتك للمقدّم…",
    "You can only forward a submission you made while signed in.": "يمكنك إحالة تقديم أرسلته وأنت مسجّل الدخول فقط.",
    "You can only remove attachments you uploaded. Respondent files are removed from the public track page.": "يمكنك إزالة المرفقات التي رفعتها فقط. ملفات المستجيب تُزال من صفحة التتبع العامة.",
    "You can undo your last approval for a few minutes. The submission timeline records the reversal.": "يمكنك التراجع عن آخر اعتماد لدقائق. يُسجّل الخط الزمني ذلك.",
    "You cannot open this related form": "لا يمكنك فتح هذا النموذج المرتبط",
    "You do not have permission to remove this attachment.": "ليس لديك إذن لإزالة هذا المرفق.",
    "You have no pending related forms.": "لا نماذج مرتبطة معلّقة لديك.",
    "Your answers merged into this form’s print template. Anyone with this tracking link can download these files — keep the link private.": "دُمجت إجاباتك في قالب الطباعة. أي شخص لديه رابط التتبع يمكنه التنزيل — احفظ الرابط سرًا.",
    "Your organization slug, a hyphen, then your username (e.g. mosa-kuwait-jdoe).": "معرّف منظمتك، شرطة، ثم اسم المستخدم (مثل mosa-kuwait-jdoe).",
    "Your private note": "ملاحظتك الخاصة",
    "Your private sticky note": "ملاحظتك اللاصقة الخاصة",
    "Your submission to {{form_title}} was accepted": "قُبل تقديمك إلى {{form_title}}",
    "Your submission to {{form_title}} was received": "استُلم تقديمك إلى {{form_title}}",
    'e.g. "@company"': 'مثل "@company"',
    "e.g. 200": "مثل 200",
    "e.g. 5": "مثل 5",
    "e.g. call applicant Friday": "مثل: اتصال بالمقدّم يوم الجمعة",
    "e.g. follow-up, legal, q1-2026": "مثل: متابعة، قانوني، q1-2026",
    "e.g. pending TOEFL registrations from last week": "مثل: تسجيلات TOEFL المعلّقة من الأسبوع الماضي",
    'form field “%(label)s”': 'حقل النموذج «%(label)s»',
    "signed-in applicant account email": "بريد حساب المقدّم المسجّل",
}

FUZZY_FIXES: dict[str, str] = {
    "%(n)s submission(s) match.": "تطابق %(n)s تقديمًا.",
    "<strong>Fields.</strong> Add questions with types such as short text, paragraph, email, number, date, dropdown, radio, checkbox, checklist, and file upload. Each field has an <strong>internal name</strong> (letters, numbers, hyphens): that name is what you use in print templates and APIs of merge.": "<strong>الحقول.</strong> أضف أسئلة بأنواع مثل نص قصير، فقرة، بريد، رقم، تاريخ، قائمة، راديو، خانة اختيار، قائمة تحقق، ورفع ملف. لكل حقل <strong>اسم داخلي</strong> (حروف وأرقام وشرطات): يُستخدم في قوالب الطباعة ودمج API.",
    "<strong>Related forms (optional).</strong> Link a “child” form to a parent form so selected applicants can complete an extra questionnaire after the main submission.": "<strong>نماذج مرتبطة (اختياري).</strong> اربط نموذجًا فرعيًا بالأصل ليتمكن مختارون من استبيان إضافي بعد التقديم الرئيسي.",
    "Action needed": "إجراء مطلوب",
    "Active on public portal": "نشط في البوابة العامة",
    "Add a message": "إضافة رسالة",
    "Add link": "إضافة رابط",
    "Add related form": "إضافة نموذج مرتبط",
    "Add signature images (PNG, JPEG, GIF, WebP, SVG), up to %(lim)s per user. Removing an image is not available here; the employee can do that from “My signatures” if your policy allows. The primary image is used first in merged documents; use “Set as primary” on a row below. Uploads are separate from the account form above.": "أضف صور توقيع (PNG، JPEG، GIF، WebP، SVG)، حتى %(lim)s لكل مستخدم. الإزالة غير متاحة هنا؛ يمكن للموظف ذلك من «توقيعاتي». الصورة الأساسية تُستخدم أولًا في المستندات المدمجة.",
    "All connections": "كل الارتباطات",
    "All organizations": "كل المنظمات",
    "All organizations (default)": "كل المنظمات (افتراضي)",
    "Anyone can use public forms and organization portals without signing in. Use this page to sign in to MagicForms: <strong>superusers</strong> and <strong>staff</strong> use the full studio for their organizations; <strong>employees and applicants</strong> who belong to an organization can open their home after sign-in to reach published forms and their own submissions.": "يمكن لأي شخص استخدام النماذج العامة وبوابات المنظمات دون تسجيل دخول. استخدم هذه الصفحة لتسجيل الدخول إلى MagicForms: <strong>المشرفون الأعلى</strong> و<strong>الموظفون</strong> يستخدمون الاستوديو الكامل؛ <strong>الموظفون والمتقدمون</strong> التابعون لمنظمة يفتحون صفحتهم بعد الدخول.",
    "Ask a question or leave a note for others on this submission…": "اطرح سؤالًا أو اترك ملاحظة للآخرين على هذا التقديم…",
    "Assignee": "المكلّف",
    "Attachment removed (manage): %(name)s": "أُزيل المرفق (إدارة): %(name)s",
    "Attachment removed: %(name)s": "أُزيل المرفق: %(name)s",
    "Back to form in studio": "العودة إلى النموذج في الاستوديو",
    "Background tint": "لون تظليل الخلفية",
    "Caption": "تسمية توضيحية",
    "Close preview": "إغلاق المعاينة",
    "Complete form": "إكمال النموذج",
    "Complete related form": "إكمال النموذج المرتبط",
    "Configure organization email": "ضبط بريد المنظمة",
    "Deadline (optional)": "الموعد النهائي (اختياري)",
    "Document preview": "معاينة المستند",
    "Download DOCX": "تنزيل DOCX",
    "Download ODT": "تنزيل ODT",
    "Download timeline as PDF": "تنزيل الخط الزمني كـ PDF",
    "Open full timeline": "فتح الخط الزمني الكامل",
    "Submission timeline": "الخط الزمني للتقديم",
    "Download PDF": "تنزيل PDF",
    "Share timeline": "مشاركة الخط الزمني",
    "Share with colleagues": "مشاركة مع الزملاء",
    "People with timeline access": "من لديهم وصول للخط الزمني",
    "Timeline sharing updated.": "تم تحديث مشاركة الخط الزمني.",
    "You cannot change timeline sharing for this submission.": "لا يمكنك تغيير مشاركة الخط الزمني لهذا التقديم.",
    "Back to home": "العودة إلى الرئيسية",
    "Grant anyone in this organization (staff or end users) access to this timeline page. They will not see the full submission manage screen unless they already have access through workflow or search.": "امنح أي شخص في المنظمة (مشرف أو مستخدم نهائي) وصولًا لصفحة الخط الزمني. لن يروا شاشة إدارة التقديم الكاملة إلا إن كان لديهم وصول مسبق عبر سير العمل أو البحث.",
    "Shared timelines": "خطوط زمنية مُشاركة",
    "Submission timelines shared with you. Open one to read the history; you do not get the full manage submission page unless you already have workflow or search access.": "خطوط زمنية لتقديمات شاركها معك آخرون. افتح أحدها لقراءة السجل؛ لا تحصل على صفحة إدارة التقديم الكاملة إلا إن كان لديك وصول عبر سير العمل أو البحث.",
    "Open timeline": "فتح الخط الزمني",
    "Shared by %(who)s": "شاركه %(who)s",
    "Timeline link": "رابط الخط الزمني",
    "Shared colleagues see this timeline under Home → Shared timelines, or you can send them the link below.": "يرى الزملاء المشاركون هذا الخط الزمني في الرئيسية → خطوط زمنية مُشاركة، أو أرسل لهم الرابط أدناه.",
    "Shared colleagues see this timeline under Home → Shared timelines.": "يرى الزملاء المشاركون هذا الخط الزمني في الرئيسية → خطوط زمنية مُشاركة.",
    "No timelines shared with you yet.": "لا توجد خطوط زمنية مُشاركة معك بعد.",
    "Choose at least one colleague to share with, then click Update sharing.": "اختر زميلًا واحدًا على الأقل للمشاركة، ثم اضغط تحديث المشاركة.",
    "Timeline shared with %(count)d colleague(s). They will see it on Home under Shared timelines.": "تمت مشاركة الخط الزمني مع %(count)d زميل/زملاء. سيظهر لهم في الرئيسية ضمن الخطوط الزمنية المُشاركة.",
    "Message for colleagues (optional)": "رسالة للزملاء (اختياري)",
    "Shown on their Home list and at the top of the timeline when they open it.": "تظهر في قائمة الرئيسية وفي أعلى الخط الزمني عند فتحه.",
    "Message from sharer": "رسالة من المشارك",
    "Remove from my list": "إزالة من قائمتي",
    "Remove": "إزالة",
    "Removed from your shared timelines list.": "أُزيل من قائمة الخطوط الزمنية المُشاركة.",
    "Not opened yet": "لم يُفتح بعد",
    "Remove this shared timeline from your list?": "إزالة هذا الخط الزمني المُشارك من قائمتك؟",
    "Remove this shared timeline from your Home list?": "إزالة هذا الخط الزمني من قائمة الرئيسية؟",
    "Duplicate field": "نسخ الحقل",
    "Edit logo": "تحرير الشعار",
    "Edit tags": "تحرير الوسوم",
    "Email notification templates": "قوالب إشعارات البريد",
    "Email on file": "البريد المسجّل",
    "Email templates": "قوالب البريد",
    "Enter a question to search your inbox.": "أدخل سؤالًا للبحث في صندوق الوارد.",
    "Features": "الميزات",
    "Field basics": "أساسيات الحقل",
    "Filled form document": "مستند النموذج المعبّأ",
    "Form hub": "مركز النموذج",
    "Form logos and title": "شعارات النموذج والعنوان",
    "Form not found.": "لم يُعثر على النموذج.",
    "Forward submission": "إحالة التقديم",
    "Found %(n)s submission(s) you can open below.": "وُجد %(n)s تقديمًا يمكنك فتحه أدناه.",
    "If you think this is a mistake, contact the form owner. Studio users can open the": "إن اعتقدت أن هذا خطأ، تواصل مع مالك النموذج. يمكن لمستخدمي الاستوديو فتح",
    "Last saved": "آخر حفظ",
    "Leave blank when editing to keep the current SMTP password.": "اتركه فارغًا عند التحرير للاحتفاظ بكلمة مرور SMTP الحالية.",
    "Link a related form": "ربط نموذج مرتبط",
    "Loading document…": "جارٍ تحميل المستند…",
    "Loading…": "جارٍ التحميل…",
    "Logo updated.": "تم تحديث الشعار.",
    "Main form": "النموذج الرئيسي",
    "No additional documents.": "لا مستندات إضافية.",
    "No answer": "لا إجابة",
    "No matching submissions.": "لا تقديمات مطابقة.",
    "No messages yet.": "لا رسائل بعد.",
    "No related forms linked yet.": "لا نماذج مرتبطة بعد.",
    "No step": "لا خطوة",
    "No submissions matched. Try different words or use the filters above.": "لا تقديمات مطابقة. جرّب كلمات أخرى أو المرشحات أعلاه.",
    "Not yet submitted": "لم يُرسل بعد",
    "Note (optional)": "ملاحظة (اختياري)",
    "Numbers and dates": "الأرقام والتواريخ",
    "Open matching list in submission search": "فتح القائمة المطابقة في بحث التقديمات",
    "Open submission (studio)": "فتح التقديم (الاستوديو)",
    "Optional note": "ملاحظة اختيارية",
    "Optional text shown under the image in the slideshow.": "نص اختياري يظهر تحت الصورة في العرض.",
    "Optional validation": "تحقق اختياري",
    "Organization home": "الصفحة الرئيسية للمنظمة",
    "Organization logo": "شعار المنظمة",
    "Organization not found": "لم تُعثر على المنظمة",
    "Organization not found.": "لم تُعثر على المنظمة.",
    "Organization settings": "إعدادات المنظمة",
    "Organization username": "اسم مستخدم المنظمة",
    "PNG, JPEG, GIF, WebP, or SVG. Maximum three logos per form (one per position).": "PNG أو JPEG أو GIF أو WebP أو SVG. ثلاثة شعارات كحد أقصى لكل نموذج (واحد لكل موضع).",
    "PNG, JPEG, GIF, WebP, or SVG. Up to %(lim)s images.": "PNG أو JPEG أو GIF أو WebP أو SVG. حتى %(lim)s صورة.",
    "Presentation": "العرض",
    "Primary color": "اللون الأساسي",
    "Question": "سؤال",
    "Rejection reason (required)": "سبب الرفض (مطلوب)",
    "Related form": "نموذج مرتبط",
    "Related form link saved.": "تم حفظ رابط النموذج المرتبط.",
    "Related forms": "نماذج مرتبطة",
    "Related forms to complete": "نماذج مرتبطة لإكمالها",
    "Related invitations appear in “Forms to complete” when the workflow creates them.": "تظهر الدعوات المرتبطة في «نماذج لإكمالها» عند إنشائها من سير العمل.",
    "Related link removed.": "أُزيل الرابط المرتبط.",
    "Remove tag": "إزالة الوسم",
    "Remove this related link?": "إزالة هذا الرابط المرتبط؟",
    "Remove this tag?": "إزالة هذا الوسم؟",
    "Respondent": "المستجيب",
    "Save note": "حفظ الملاحظة",
    "Save tags": "حفظ الوسوم",
    "Saved": "محفوظ",
    "Saved text": "النص المحفوظ",
    "Search submissions": "بحث التقديمات",
    "Send email": "إرسال بريد",
    "Set an SMTP host in organization email settings.": "حدّد مضيف SMTP في إعدادات بريد المنظمة.",
    "Share form": "مشاركة النموذج",
    "Signature image saved.": "تم حفظ صورة التوقيع.",
    "Studio scope: %(name)s.": "نطاق الاستوديو: %(name)s.",
    "Studio scope: all organizations.": "نطاق الاستوديو: كل المنظمات.",
    "Subject": "الموضوع",
    "Submission not found.": "لم يُعثر على التقديم.",
    "Submitted": "تاريخ الإرسال",
    "Tag removed.": "أُزيل الوسم.",
    "Theme 1 background tint": "تظليل خلفية السمة 1",
    "Theme 1 primary color": "اللون الأساسي للسمة 1",
    "Theme 1 secondary color": "اللون الثانوي للسمة 1",
    "Theme 2 background tint": "تظليل خلفية السمة 2",
    "Theme 2 primary color": "اللون الأساسي للسمة 2",
    "Theme 2 secondary color": "اللون الثانوي للسمة 2",
    "Theme 3 background tint": "تظليل خلفية السمة 3",
    "Theme 3 primary color": "اللون الأساسي للسمة 3",
    "Theme 3 secondary color": "اللون الثانوي للسمة 3",
    "This field must exactly match the required value.": "يجب أن يطابق هذا الحقل القيمة المطلوبة بالضبط.",
    "This form is already archived.": "هذا النموذج مؤرشف بالفعل.",
    "This form is not archived.": "هذا النموذج غير مؤرشف.",
    "Undo approve": "التراجع عن الاعتماد",
    "Unknown action.": "إجراء غير معروف.",
    "Up to three images (PNG, JPEG, GIF, WebP, or SVG). Choose left, center (above title), or right for each.": "حتى ثلاث صور (PNG، JPEG، GIF، WebP، SVG). اختر يسارًا أو وسطًا (فوق العنوان) أو يمينًا لكل منها.",
    "When submission reaches this step": "عند وصول التقديم لهذه الخطوة",
    "With answer": "مع إجابة",
    "Workflow status": "حالة سير العمل",
    "You can have at most %(max)d signature images.": "يمكنك %(max)d صورة توقيع كحد أقصى.",
    "You must be signed in.": "يجب تسجيل الدخول.",
    "Your signature images": "صور توقيعك",
    "Your submission": "تقديمك",
    "Your tag": "وسمك",
    "Your tags": "وسومك",
    "Your tags were updated.": "تم تحديث وسومك.",
    "at step": "في الخطوة",
    "email on file for this submission": "البريد المسجّل لهذا التقديم",
    "signature on file": "توقيع مسجّل",
    "“Not after” date must be on or after “Not before”.": "يجب أن يكون تاريخ «ليس بعد» في أو بعد «ليس قبل».",
    # Submission timeline (UI + PDF)
    "Form submitted.": "تم إرسال النموذج.",
    "Workflow rejected; stopped at this step.": "رُفض سير العمل؛ توقّف عند هذه الخطوة.",
    "All workflow steps approved; submission complete.": "اعُتمدت كل خطوات سير العمل؛ اكتمل التقديم.",
    'Approved; advanced to "%(step)s".': 'اعتماد؛ الانتقال إلى «%(step)s».',
    "Comment:": "تعليق:",
    "Document added: %(file)s": "أُضيف مستند: %(file)s",
    "Document added (manage): %(file)s": "أُضيف مستند (إدارة): %(file)s",
    "Document added: %(file)s — %(title)s": "أُضيف مستند: %(file)s — %(title)s",
    "Document added (manage): %(file)s — %(title)s": "أُضيف مستند (إدارة): %(file)s — %(title)s",
    "Attachment removed: %(name)s": "أُزيل مرفق: %(name)s",
    "Attachment removed (manage): %(name)s": "أُزيل مرفق (إدارة): %(name)s",
    "Email sent to applicant (%(addr)s): %(subject)s": "أُرسل بريد إلى مقدّم الطلب (%(addr)s): %(subject)s",
    "Forwarded to %(user)s": "أُحيل إلى %(user)s",
    "Forwarded to %(user)s (%(name)s)": "أُحيل إلى %(user)s (%(name)s)",
    "Forwarded to %(user)s\nNote: %(note)s": "أُحيل إلى %(user)s\nملاحظة: %(note)s",
    "Forwarded to %(user)s (%(name)s)\nNote: %(note)s": "أُحيل إلى %(user)s (%(name)s)\nملاحظة: %(note)s",
    'Related form available: "%(title)s". Complete it using the link in the related forms section below.': (
        'نموذج مرتبط متاح: «%(title)s». أكمله من الرابط في قسم النماذج المرتبطة أدناه.'
    ),
    'Related form submitted: "%(title)s".': 'أُرسل النموذج المرتبط: «%(title)s».',
}
# pgettext contexts (timeline kinds vs grid “Submitted” date label).
TIMELINE_PCONTEXT: dict[str, dict[str, str]] = {
    "timeline event": {
        "Submitted": "تم الإرسال",
        "Workflow step changed": "تغيّرت خطوة سير العمل",
        "Note": "ملاحظة",
        "Step approved": "تم اعتماد الخطوة",
        "Workflow completed": "اكتمل سير العمل",
        "Approval undone": "تم التراجع عن الاعتماد",
        "Workflow rejected": "رُفض سير العمل",
        "Document attached": "أُرفق مستند",
        "Forwarded": "أُحيل",
        "Related form available": "نموذج مرتبط متاح",
        "Related form submitted": "أُرسل النموذج المرتبط",
    },
    "timeline delegate": {
        " [delegate for: %(names)s]": " [نيابة عن: %(names)s]",
        " [delegate]": " [نيابة]",
    },
}
PLURALS: dict[str, dict[str, str]] = {
    "%%(counter)s field": {
        "0": "%%(counter)s حقل",
        "1": "حقل %%(counter)s",
        "2": "حقلان %%(counter)s",
        "3": "%%(counter)s حقول",
        "4": "%%(counter)s حقول",
        "5": "%%(counter)s حقول",
    },
}
