# Generated by Django 5.2.14 on 2026-05-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='inline',
            field=models.BooleanField(default=False, help_text='Show on the same row as neighboring fields that are also set to inline.', verbose_name='Inline row'),
        ),
    ]
