# Generated by Django 5.2.14 on 2026-05-10 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0002_formfield_inline'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='visibility_control_field',
            field=models.ForeignKey(blank=True, help_text='Optional: another field whose value controls whether this field is shown.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visibility_dependent_fields', to='magicforms.formfield'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='visibility_show_when_values',
            field=models.TextField(blank=True, help_text='When the control field equals any line below (one per line), this field is visible. For checkboxes use yes or leave blank for unchecked.'),
        ),
    ]
