# Generated by Django 5.2.14 on 2026-05-11 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0003_formfield_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('starts_collapsed', models.BooleanField(default=False, help_text='When on, the section is closed until the respondent taps to expand it.', verbose_name='Starts collapsed')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='magicforms.form')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Optional: place this field inside a collapsible section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='magicforms.formsection'),
        ),
    ]
