# Generated by Django 5.2.14 on 2026-05-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0004_form_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='mapping_key',
            field=models.CharField(blank=True, help_text='Optional: User or profile attribute to pre-fill for signed-in users (e.g. email, first_name, job_title). Matches User fields, then user.profile if it exists.', max_length=80, verbose_name='Mapping name'),
        ),
    ]
