# Generated by Django 5.2.14 on 2026-05-11 10:33

import magicforms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0005_formfield_mapping_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionvalue',
            name='attachment',
            field=models.FileField(blank=True, help_text='Populated when the form field type is file upload.', max_length=500, upload_to=magicforms.models.submission_value_attachment_upload_to, verbose_name='Uploaded file'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short text'), ('textarea', 'Paragraph'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('radio', 'Radio buttons'), ('checkbox', 'Checkbox'), ('file', 'File upload')], default='text', max_length=32),
        ),
    ]
