# Generated by Django 5.2.14 on 2026-05-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0006_file_field_and_submission_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='submission_deadline',
            field=models.DateField(blank=True, help_text='If set, respondents cannot submit after this calendar date (end of day in the site time zone).', null=True, verbose_name='Submission deadline'),
        ),
    ]
