# Generated by Django 5.2.14 on 2026-05-11 13:47

import django.db.models.deletion
from django.db import migrations, models


def seed_default_categories(apps, schema_editor):
    FormCategory = apps.get_model("magicforms", "FormCategory")
    seeds = [
        ("Human Resources", "hr", 0),
        ("Finance", "finance", 10),
        ("IT", "it", 20),
        ("Operations", "operations", 30),
        ("Legal", "legal", 40),
        ("Marketing", "marketing", 50),
        ("General", "general", 100),
    ]
    for name, slug, order in seeds:
        if not FormCategory.objects.filter(slug=slug).exists():
            FormCategory.objects.create(name=name, slug=slug, order=order)


def unseed_default_categories(apps, schema_editor):
    FormCategory = apps.get_model("magicforms", "FormCategory")
    FormCategory.objects.filter(
        slug__in=["hr", "finance", "it", "operations", "legal", "marketing", "general"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0007_form_submission_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Form categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='form',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional group such as HR or Finance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='magicforms.formcategory'),
        ),
        migrations.RunPython(seed_default_categories, unseed_default_categories),
    ]
