# Generated by Django 5.2.14 on 2026-05-11 13:50

import django.core.validators
import django.db.models.deletion
import magicforms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0008_form_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=500, upload_to=magicforms.models.form_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg'])], verbose_name='Logo file')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='magicforms.form')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
