# Generated by Django 5.2.14 on 2026-05-11 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0010_workflow_step_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='print_template',
            field=models.FileField(blank=True, help_text="Optional. DOCX: use Jinja placeholders like {{ field_name }} matching each field's internal name (underscores; hyphens in names map to underscores). PDF: fillable AcroForm fields must use the same names as field internal slugs. Also: form_title, submitter_email, reference_token, submitted_at, current_step_label.", max_length=500, upload_to='form_print_templates/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'pdf'])], verbose_name='Print template (DOCX or PDF)'),
        ),
    ]
