# Generated by Django 5.2.14 on 2026-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0011_form_print_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='workflow_state',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='in_progress', help_text='Staff approve/reject drives progression; completed or rejected stops the inbox queue.', max_length=20),
        ),
        migrations.AlterField(
            model_name='submissionevent',
            name='kind',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('step_changed', 'Workflow step changed'), ('note', 'Note'), ('step_approved', 'Step approved'), ('workflow_completed', 'Workflow completed'), ('workflow_rejected', 'Workflow rejected')], max_length=32),
        ),
    ]
