# Generated by Django 5.2.14 on 2026-05-11 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_employee_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    EmployeeProfile = apps.get_model("magicforms", "EmployeeProfile")
    for row in User.objects.all().iterator():
        EmployeeProfile.objects.get_or_create(user_id=row.pk)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('magicforms', '0012_formsubmission_workflow_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_number', models.CharField(blank=True, db_index=True, help_text='Internal employee or payroll ID.', max_length=64, null=True, unique=True)),
                ('civil_id', models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True, verbose_name='Civil / national ID')),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, help_text='e.g. Bachelor of Science, MBA.', max_length=200, verbose_name='Highest degree')),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('intern', 'Intern'), ('other', 'Other')], default='full_time', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('', '— Prefer not to say —'), ('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('other', 'Other')], default='', max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('work_phone', models.CharField(blank=True, max_length=40)),
                ('mobile_phone', models.CharField(blank=True, max_length=40, verbose_name='Personal mobile')),
                ('work_email', models.EmailField(blank=True, help_text='Optional; defaults to account email if empty for directory display.', max_length=254)),
                ('office_location', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True, help_text='Internal HR notes — not shown on public forms.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Direct manager (directory / org chart).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee profile',
                'verbose_name_plural': 'Employee profiles',
            },
        ),
        migrations.RunPython(backfill_employee_profiles, noop_reverse),
    ]
