# Generated by Django 5.2.14 on 2026-05-11 16:25

import django.core.validators
import django.db.models.deletion
import magicforms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0013_employee_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='mapping_key',
            field=models.CharField(blank=True, help_text='Optional: User or profile attribute to pre-fill for signed-in users (e.g. email, first_name, job_title, civil_id, employee_number, department, age). Matches User fields, then user.profile (EmployeeProfile) if it exists.', max_length=80, verbose_name='Mapping name'),
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Optional label, e.g. Primary, Arabic, or Contract copy.', max_length=120)),
                ('image', models.FileField(max_length=500, upload_to=magicforms.models.user_signature_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg'])], verbose_name='Signature image')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
