# Generated by Django 5.2.14 on 2026-05-11 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0014_user_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='one_time_submit',
            field=models.BooleanField(default=False, help_text='When on, each signed-in account may submit at most once. Anonymous visitors are limited by email (if provided) and by this browser session after a successful submit.', verbose_name='One response per respondent'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Set when the respondent was signed in at submit time (used for one-response enforcement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
