# Generated by Django 5.2.14 on 2026-05-11 16:33

import django.core.validators
import django.db.models.deletion
import magicforms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0015_form_one_time_submit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionevent',
            name='kind',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('step_changed', 'Workflow step changed'), ('note', 'Note'), ('step_approved', 'Step approved'), ('workflow_completed', 'Workflow completed'), ('workflow_rejected', 'Workflow rejected'), ('attachment_added', 'Document attached')], max_length=32),
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional label shown next to the download link.', max_length=200)),
                ('file', models.FileField(max_length=500, upload_to=magicforms.models.submission_user_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'txt', 'csv', 'xlsx', 'xls'])], verbose_name='Document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_attachments', to='magicforms.formsubmission')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Staff user when uploaded from manage; empty when uploaded from the public track page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
