# Generated by Django 5.2.14 on 2026-05-11 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0016_submission_document_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, help_text='Optional. First calendar day this delegation applies; blank = immediately.', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Optional. Last calendar day this delegation applies; blank = no end date.', null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_delegations_created', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(help_text='Staff user who may act on their behalf.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_delegations_received', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(help_text='Assignee who is covered (out of office, etc.).', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_delegations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
