# Generated by Django 5.2.14 on 2026-05-11 17:43

import django.core.validators
import magicforms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0019_entity_public_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='show_on_public_directory',
            field=models.BooleanField(default=True, help_text='List this organization on the global home page directory.'),
        ),
        migrations.AlterField(
            model_name='form',
            name='print_template',
            field=models.FileField(blank=True, help_text="Optional. DOCX: use Jinja placeholders like {{ field_name }} matching each field's internal name (underscores; hyphens in names map to underscores). ODT: stored for staff download and optional PDF preview via LibreOffice; answers are not merged into ODT. PDF: fillable AcroForm fields must use the same names as field internal slugs. Also: form_title, submitter_email, reference_token, submitted_at, current_step_label.", max_length=500, upload_to='form_print_templates/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'odt', 'pdf'])], verbose_name='Print template (DOCX, ODT, or PDF)'),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=magicforms.models.submission_user_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'txt', 'csv', 'xlsx', 'xls', 'odt'])], verbose_name='Document'),
        ),
    ]
