# Generated by Django 5.2.14 on 2026-05-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0020_print_template_and_attachment_odt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='one_time_submit',
            field=models.BooleanField(default=False, help_text='When on, each signed-in account may submit at most once. Visitors who are not signed in are limited to one submit per browser (session) after a successful response.', verbose_name='One response per respondent'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='submitter_email',
            field=models.EmailField(blank=True, help_text='Account email when the respondent was signed in; otherwise usually blank.', max_length=254),
        ),
    ]
