# Generated by Django 5.2.14 on 2026-05-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0021_remove_public_submitter_email_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='submitter_email',
            field=models.EmailField(blank=True, help_text='When the respondent was signed in, their account email is copied here on submit; otherwise this stays blank (anonymous in the database).', max_length=254),
        ),
    ]
