# Generated by Django 5.2.14 on 2026-05-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0023_entity_page_logo_help_logo_knockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='validation_date_after',
            field=models.DateField(blank=True, help_text='Date fields must be on or after this calendar day.', null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_date_before',
            field=models.DateField(blank=True, help_text='Date fields must be on or before this calendar day.', null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_decimal_max',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Numeric fields: largest allowed number (inclusive).', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_decimal_min',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Numeric fields: smallest allowed number (inclusive).', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_integer_only',
            field=models.BooleanField(default=False, help_text='When on, numeric fields must not use decimals.'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_max_length',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum character count. Also bounds the HTML input limit for short text / paragraph.', null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_min_length',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum character count (after trimming). Applies to short text, paragraph, email, dropdown, radio.', null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_must_contain',
            field=models.CharField(blank=True, help_text='Substring that must appear (case-insensitive), e.g. "@" or a code word.', max_length=500),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_must_equal',
            field=models.CharField(blank=True, help_text='If set, the submitted value must match this text exactly (after trimming).', max_length=500),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_must_not_contain',
            field=models.CharField(blank=True, help_text='Substring that must not appear (case-insensitive).', max_length=500),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validation_regex',
            field=models.CharField(blank=True, help_text='Optional regex checked against the value (Python re syntax), e.g. ^[A-Z]{3}-\\d{4}$.', max_length=500),
        ),
    ]
