# Generated by Django 5.2.14 on 2026-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0024_formfield_validation_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when a super admin archives this form (soft delete). Archived forms are hidden from public and normal studio lists.', null=True),
        ),
    ]
