# Generated by Django 5.2.14 on 2026-05-11 19:31

import django.core.validators
from django.core.files.base import ContentFile
from django.db import migrations, models


def migrate_odt_files_forward(apps, schema_editor):
    """Move legacy single-field .odt uploads from print_template to print_template_odt."""
    Form = apps.get_model("magicforms", "Form")
    for form in Form.objects.exclude(print_template=""):
        path = form.print_template.name
        if not path.lower().endswith(".odt"):
            continue
        try:
            form.print_template.open("rb")
            data = form.print_template.read()
        finally:
            form.print_template.close()
        base = path.split("/")[-1] or "template.odt"
        form.print_template_odt.save(base, ContentFile(data), save=False)
        form.print_template.delete(save=False)
        form.save()


def migrate_odt_files_backward(apps, schema_editor):
    Form = apps.get_model("magicforms", "Form")
    for form in Form.objects.exclude(print_template_odt=""):
        path = form.print_template_odt.name
        try:
            form.print_template_odt.open("rb")
            data = form.print_template_odt.read()
        finally:
            form.print_template_odt.close()
        base = path.split("/")[-1] or "template.odt"
        form.print_template.save(base, ContentFile(data), save=False)
        form.print_template_odt.delete(save=False)
        form.save()


class Migration(migrations.Migration):

    dependencies = [
        ("magicforms", "0025_form_soft_delete_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="print_template_odt",
            field=models.FileField(
                blank=True,
                help_text="Optional. ODT copy for download and editing in LibreOffice; answers are not merged into this file. Use the DOCX or PDF template above for merged outputs with submission data.",
                max_length=500,
                upload_to="form_print_templates/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["odt"])
                ],
                verbose_name="Print template (ODT, optional)",
            ),
        ),
        migrations.RunPython(migrate_odt_files_forward, migrate_odt_files_backward),
        migrations.AlterField(
            model_name="form",
            name="print_template",
            field=models.FileField(
                blank=True,
                help_text="Optional primary template for merged documents. DOCX: Jinja placeholders like {{ field_name }} matching each field internal name (underscores; hyphens map to underscores). PDF: fillable AcroForm field names match internal slugs. Also: form_title, submitter_email, reference_token, submitted_at, current_step_label. Upload a separate ODT below if you want an editable LibreOffice copy for staff.",
                max_length=500,
                upload_to="form_print_templates/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["docx", "pdf"]
                    )
                ],
                verbose_name="Print template (DOCX or PDF)",
            ),
        ),
    ]
