# Generated by Django 5.2.14 on 2026-05-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0026_form_print_template_odt_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='allow_submission_forward',
            field=models.BooleanField(default=False, help_text='When on, staff can record that a submission was forwarded to another user (shown on the timeline).', verbose_name='Allow forwarding submissions'),
        ),
        migrations.AlterField(
            model_name='submissionevent',
            name='kind',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('step_changed', 'Workflow step changed'), ('note', 'Note'), ('step_approved', 'Step approved'), ('workflow_completed', 'Workflow completed'), ('workflow_rejected', 'Workflow rejected'), ('attachment_added', 'Document attached'), ('forwarded', 'Forwarded')], max_length=32),
        ),
    ]
