# Generated by Django 5.2.14 on 2026-05-11 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0027_form_allow_submission_forward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionevent',
            name='kind',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('step_changed', 'Workflow step changed'), ('note', 'Note'), ('step_approved', 'Step approved'), ('workflow_completed', 'Workflow completed'), ('workflow_rejected', 'Workflow rejected'), ('attachment_added', 'Document attached'), ('forwarded', 'Forwarded'), ('supplementary_invited', 'Supplementary form available'), ('supplementary_submitted', 'Supplementary form submitted')], max_length=32),
        ),
        migrations.CreateModel(
            name='SupplementaryFormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_links_in', to='magicforms.form')),
                ('parent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_links_out', to='magicforms.form')),
                ('trigger_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_link_triggers', to='magicforms.workflowstep')),
            ],
        ),
        migrations.CreateModel(
            name='SupplementarySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('child_submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplementary_slot', to='magicforms.formsubmission')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='magicforms.supplementaryformlink')),
                ('parent_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_instances', to='magicforms.formsubmission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='supplementaryformlink',
            constraint=models.UniqueConstraint(fields=('parent_form', 'child_form', 'trigger_step'), name='uniq_supplementary_parent_child_trigger'),
        ),
        migrations.AddConstraint(
            model_name='supplementarysubmission',
            constraint=models.UniqueConstraint(fields=('link', 'parent_submission'), name='uniq_supplementary_invite_per_parent_submission'),
        ),
    ]
