# Generated by Django 5.2.14 on 2026-05-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0028_supplementary_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_for_public',
            field=models.BooleanField(default=True, help_text='When on, anyone with the link can open and submit this form without an account. When off, only signed-in users can use the form (anonymous visitors are sent to sign in).', verbose_name='Allow access without signing in'),
        ),
    ]
