# Generated by Django 5.2.14 on 2026-05-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0029_form_is_for_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='public_share_key',
            field=models.UUIDField(blank=True, db_index=True, help_text='Optional secret segment for public links. When set, the form only opens when the URL includes ?share=<this uuid> (QR codes include it). Regenerate on the Share QR page to invalidate old prints.', null=True),
        ),
    ]
