# Generated by Django 5.2.14 on 2026-05-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0030_form_public_share_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='hide_from_form_lists',
            field=models.BooleanField(default=False, help_text='When on, this form is omitted from the organization public portal, the global home directory, and the studio dashboard list (useful for supplementary-only or parent-driven forms). Direct links, QR codes, submissions, and studio form pages still work.', verbose_name='Hide from portal & dashboard lists'),
        ),
    ]
