# Generated by Django 5.2.14 on 2026-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0032_staff_inbox_submission_detail_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='hide_from_form_lists',
            field=models.BooleanField(default=False, help_text='When on, this form is omitted from the organization public portal, the global home directory, and the studio home form list (useful for supplementary-only or parent-driven forms). Direct links, QR codes, submissions, and studio form pages still work.', verbose_name='Hide from portal & home lists'),
        ),
    ]
