# Generated by Django 5.2

from collections import defaultdict

from django.db import migrations, models


def assign_header_slots(apps, schema_editor):
    FormLogo = apps.get_model("magicforms", "FormLogo")
    by_form = defaultdict(list)
    for logo in FormLogo.objects.all().order_by("form_id", "sort_order", "id"):
        by_form[logo.form_id].append(logo)
    LEFT, CENTER, RIGHT = 0, 1, 2
    for logos in by_form.values():
        logos = list(logos)
        n = len(logos)
        if n >= 3:
            slots = [LEFT, CENTER, RIGHT]
        elif n == 2:
            slots = [LEFT, RIGHT]
        elif n == 1:
            slots = [LEFT]
        else:
            continue
        for logo, slot in zip(logos, slots):
            logo.header_slot = slot
            logo.sort_order = slot
            logo.save(update_fields=["header_slot", "sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("magicforms", "0033_rename_dashboard_copy_to_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="formlogo",
            name="header_slot",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
            ),
        ),
        migrations.RunPython(assign_header_slots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="formlogo",
            name="header_slot",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Left (beside title column)"),
                    (1, "Center (above title)"),
                    (2, "Right (beside title column)"),
                ],
                default=0,
                help_text="Where this image appears in the live form header.",
            ),
        ),
        migrations.AddConstraint(
            model_name="formlogo",
            constraint=models.UniqueConstraint(
                fields=("form", "header_slot"),
                name="magicforms_formlogo_form_header_slot_uniq",
            ),
        ),
    ]
