# Generated by Django 5.2.14 on 2026-05-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0034_formlogo_header_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formlogo',
            options={'ordering': ['header_slot', 'id']},
        ),
        migrations.AlterField(
            model_name='formlogo',
            name='header_slot',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Left (beside title column)'), (1, 'Center (above title)'), (2, 'Right (beside title column)')], default=0, help_text='Where this image appears in the live form header.', verbose_name='Position in header'),
        ),
    ]
