# Generated by Django 5.2.14 on 2026-05-13 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0036_submission_reference_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='hide_from_form_lists',
            field=models.BooleanField(default=False, help_text='When on, this form is omitted from the organization public portal, the global home directory, and the studio home form list (useful for related-only or parent-driven forms). Direct links, QR codes, submissions, and studio form pages still work.', verbose_name='Hide from portal & home lists'),
        ),
        migrations.AlterField(
            model_name='submissionevent',
            name='kind',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('step_changed', 'Workflow step changed'), ('note', 'Note'), ('step_approved', 'Step approved'), ('workflow_completed', 'Workflow completed'), ('workflow_rejected', 'Workflow rejected'), ('attachment_added', 'Document attached'), ('forwarded', 'Forwarded'), ('supplementary_invited', 'Related form available'), ('supplementary_submitted', 'Related form submitted')], max_length=32),
        ),
        migrations.AlterField(
            model_name='supplementaryformlink',
            name='child_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links_in', to='magicforms.form'),
        ),
        migrations.AlterField(
            model_name='supplementaryformlink',
            name='parent_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links_out', to='magicforms.form'),
        ),
        migrations.AlterField(
            model_name='supplementaryformlink',
            name='trigger_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_link_triggers', to='magicforms.workflowstep'),
        ),
        migrations.AlterField(
            model_name='supplementarysubmission',
            name='child_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_invitation_slot', to='magicforms.formsubmission'),
        ),
        migrations.AlterField(
            model_name='supplementarysubmission',
            name='parent_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_invitations', to='magicforms.formsubmission'),
        ),
    ]
