# Generated by Django 5.2.14 on 2026-05-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0040_sample_forms_show_on_studio_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='choices_text',
            field=models.TextField(blank=True, help_text='For dropdown, radio, or checklist: one option per line.'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short text'), ('textarea', 'Paragraph'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('radio', 'Radio buttons'), ('checkbox', 'Checkbox'), ('checklist', 'Checklist'), ('file', 'File upload')], default='text', max_length=32),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='visibility_show_when_values',
            field=models.TextField(blank=True, help_text='When the control field matches any line below (one per line), this field is visible. For a single checkbox use yes; for a checklist use one line per option label (matches if any checked option equals a line). You can also match the exact combination by listing all selected labels as one line separated by newlines.'),
        ),
    ]
