# Generated by Django 5.2.14 on 2026-05-13 18:39

from django.db import migrations, models


def _radio_horizontal(apps, schema_editor):
    FormField = apps.get_model("magicforms", "FormField")
    FormField.objects.filter(field_type="radio").update(options_layout="horizontal")


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0041_fieldtype_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='options_layout',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='vertical', help_text='For radio buttons and checklist: show choices in a row or a column.', max_length=20, verbose_name='Display options'),
        ),
        migrations.RunPython(_radio_horizontal, _noop_reverse),
    ]
