# Generated by Django 5.2.14 on 2026-05-14 18:01

import django.core.validators
import magicforms.entity_theme
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0049_submission_user_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='active_theme_index',
            field=models.PositiveSmallIntegerField(default=0, help_text='Which of the three presets is applied on the public portal (0–2).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='login_api_active',
            field=models.BooleanField(default=False, help_text='When on, studio sign-in for this organization uses only the directory API (no Django password fallback on failure).', verbose_name='Directory login API active'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='login_api_endpoint',
            field=models.URLField(blank=True, help_text='Full URL of the directory login API (http:// or https://; JSON body: username, password). Prefer HTTPS in production.', max_length=500, verbose_name='Directory login API URL'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='login_api_key_name',
            field=models.CharField(blank=True, help_text='HTTP header for the API secret. Blank uses Authorization with a Bearer token; e.g. X-API-Key sends the raw secret in that header.', max_length=64, verbose_name='API key name'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='login_api_token',
            field=models.CharField(blank=True, help_text='Secret sent in the header named above (Bearer prefix only when the header is Authorization).', max_length=512, verbose_name='Directory login API token'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='theme_presets',
            field=models.JSONField(default=magicforms.entity_theme.default_theme_presets, help_text='Up to three portal color sets; each entry has primary, secondary, and background (hex strings).'),
        ),
        migrations.AlterField(
            model_name='submissionevent',
            name='kind',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('step_changed', 'Workflow step changed'), ('note', 'Note'), ('step_approved', 'Step approved'), ('workflow_completed', 'Workflow completed'), ('approve_undone', 'Approval undone'), ('workflow_rejected', 'Workflow rejected'), ('attachment_added', 'Document attached'), ('forwarded', 'Forwarded'), ('supplementary_invited', 'Related form available'), ('supplementary_submitted', 'Related form submitted')], max_length=32),
        ),
    ]
