# Generated by Django 5.2.14 on 2026-05-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0050_entity_login_api_endpoint_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='login_api_tenant_id',
            field=models.PositiveIntegerField(blank=True, help_text='tenant_id sent in the login API JSON body for this organization.', null=True, verbose_name='Directory login tenant ID'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='login_api_endpoint',
            field=models.URLField(blank=True, help_text='Full URL of the directory login API (http:// or https://; JSON: tenant_id, username, password). Prefer HTTPS in production.', max_length=500, verbose_name='Directory login API URL'),
        ),
    ]
