# Generated by Django 5.2.14 on 2026-05-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0051_entity_login_api_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='login_api_tenant_id',
            field=models.PositiveIntegerField(blank=True, help_text='Optional default tenant_id pre-filled on the studio sign-in page.', null=True, verbose_name='Directory login tenant ID'),
        ),
    ]
