# Generated by Django 5.2.14 on 2026-05-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0052_entity_login_api_tenant_id_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='login_api_tenant_id',
            field=models.PositiveIntegerField(blank=True, help_text='tenant_id sent in the directory login API JSON body for this organization.', null=True, verbose_name='Directory login tenant ID'),
        ),
    ]
