# Generated by Django 5.2.14 on 2026-05-17 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0053_entity_login_api_tenant_id_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignature',
            name='directory_api_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='ID from the directory login API signatures list, when synced automatically.', null=True),
        ),
        migrations.AddField(
            model_name='usersignature',
            name='directory_content_sha256',
            field=models.CharField(blank=True, help_text='SHA-256 of last imported directory signature bytes; skips re-upload when unchanged.', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='usersignature',
            constraint=models.UniqueConstraint(condition=models.Q(('directory_api_id__isnull', False)), fields=('user', 'directory_api_id'), name='magicforms_usersignature_user_directory_api_id_uniq'),
        ),
    ]
