# Generated by Django 5.2.14 on 2026-05-17 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0054_usersignature_directory_api'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdelegation',
            name='directory_api_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='ID from the directory login API delegations list, when synced automatically.', null=True),
        ),
        migrations.AddConstraint(
            model_name='workflowdelegation',
            constraint=models.UniqueConstraint(condition=models.Q(('directory_api_id__isnull', False)), fields=('entity', 'directory_api_id'), name='magicforms_workflowdelegation_entity_directory_api_id_uniq'),
        ),
    ]
