# Generated by Django 5.2.14 on 2026-05-19 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0056_form_outbound_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='formoutboundfieldmap',
            name='source_type',
            field=models.CharField(choices=[('form_field', 'Form field'), ('applicant', 'Applicant (submitter account / profile)'), ('system', 'System / workflow'), ('constant', 'Constant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formoutboundfieldmap',
            name='transform',
            field=models.CharField(choices=[('none', 'None'), ('iso_date', 'ISO date/time'), ('bool_yes_no', 'Yes / no'), ('json_array', 'Split lines to JSON array'), ('file_signed_url', 'File: signed download URL'), ('file_filename', 'File: filename only'), ('file_details', 'File: object (filename + signed URL)')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='MobileAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='magicforms__user_id_d8a033_idx')],
            },
        ),
    ]
