# Generated by Django 5.2.14 on 2026-05-21 12:11

import django.core.validators
import magicforms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0069_entity_email_notification_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formintroslide',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Announcement gallery image', 'verbose_name_plural': 'Announcement gallery images'},
        ),
        migrations.RemoveConstraint(
            model_name='mobilepushdevice',
            name='mobile_push_device_user_platform_token_uniq',
        ),
        migrations.RemoveIndex(
            model_name='mobilepushdevice',
            name='magicforms_m_user_id_6e0f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubmissiontask',
            new_name='magicforms__user_id_eaccd5_idx',
            old_name='mf_usersubtask_user_done_cr',
        ),
        migrations.AlterField(
            model_name='entity',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False, help_text='When on, all outbound email for this organization uses the SMTP settings below (studio applicant mail and future notification hooks).', verbose_name='Email notifications enabled'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='When off, automated notifications (including email) for this organization are skipped.', verbose_name='Notifications enabled'),
        ),
        migrations.AlterField(
            model_name='form',
            name='intro_details',
            field=models.TextField(blank=True, help_text='Optional. One highlight per line.', verbose_name='Highlights'),
        ),
        migrations.AlterField(
            model_name='formintroslide',
            name='image',
            field=models.ImageField(help_text='Recommended 1920×1080 px (16:9 widescreen). The slideshow is wide; other aspect ratios are centered and may be cropped.', max_length=500, upload_to=magicforms.models.form_intro_slide_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp'])], verbose_name='Gallery image'),
        ),
        migrations.AlterField(
            model_name='mobilepushdevice',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, help_text='Optional stable client id (UUID).', max_length=128),
        ),
        migrations.AlterField(
            model_name='mobilepushdevice',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='mobilepushdevice',
            index=models.Index(fields=['user', 'platform', '-updated_at'], name='magicforms__user_id_b1bc54_idx'),
        ),
        migrations.AddConstraint(
            model_name='mobilepushdevice',
            constraint=models.UniqueConstraint(fields=('user', 'platform', 'token'), name='magicforms_mobile_push_device_unique'),
        ),
    ]
