# Generated by Django 5.2.14 on 2026-05-21 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0075_reset_starter_sample_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Organization members who receive or handle submissions while they are on this step.', related_name='assigned_workflow_steps', to=settings.AUTH_USER_MODEL, verbose_name='Assignees'),
        ),
    ]
