# Generated by Django 5.1 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magicforms", "0078_submission_timeline_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissiontimelineshare",
            name="share_message",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="submissiontimelineshare",
            name="first_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submissiontimelineshare",
            name="dismissed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When set, the recipient hid this share on Home; access via share is revoked.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submissiontimelineshare",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
