# Generated by Django 5.2.14 on 2026-05-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0082_activity_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='magicforms__created_61db67_idx',
            old_name='magicforms__created_b8e0f6_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='magicforms__usernam_7dc97e_idx',
            old_name='magicforms__usernam_4a8c2d_idx',
        ),
    ]
