# Generated by Django 5.2.14 on 2026-06-10 18:05

import secrets

from django.db import migrations, models


def backfill_track_codes(apps, schema_editor):
    FormSubmission = apps.get_model("magicforms", "FormSubmission")
    batch = []
    for sub in FormSubmission.objects.filter(track_code="").only("pk").iterator(chunk_size=1000):
        sub.track_code = f"{secrets.randbelow(100000):05d}"
        batch.append(sub)
        if len(batch) >= 1000:
            FormSubmission.objects.bulk_update(batch, ["track_code"])
            batch = []
    if batch:
        FormSubmission.objects.bulk_update(batch, ["track_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0084_submissionuserhighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='track_code',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text="Short 5-digit code; with the respondent's email it opens the public track page.", max_length=5),
        ),
        migrations.RunPython(backfill_track_codes, migrations.RunPython.noop),
    ]
