# Generated by Django 5.2.14 on 2026-06-10 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0085_formsubmission_track_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionApplicantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_applicant', models.BooleanField(db_index=True, default=False)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, help_text='Staff author; empty for applicant replies from the public track page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_messages', to='magicforms.formsubmission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
