# Generated by Django 5.2.14 on 2026-06-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0087_formsubmissiondraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionuserhighlight',
            name='color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red'), ('purple', 'Purple'), ('orange', 'Orange'), ('gray', 'Gray')], max_length=16),
        ),
    ]
