# Generated by Django 5.2.14 on 2026-09-15 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0092_submission_signature_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='channel',
            field=models.CharField(choices=[('web_manage', 'Workspace'), ('web_public', 'Public site'), ('api_mobile', 'Mobile API'), ('web_other', 'Web')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False, help_text='When on, all outbound email for this organization uses the SMTP settings below (workspace applicant mail and future notification hooks).', verbose_name='Email notifications enabled'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='login_api_active',
            field=models.BooleanField(default=False, help_text='When on, workspace sign-in for this organization uses only the directory API (no Django password fallback on failure).', verbose_name='Directory login API active'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='page_logo',
            field=models.FileField(blank=True, help_text='Optional image for the workspace banner, public portal, mobile app, and directory card. For PNG, JPEG, and WebP uploads, very light backgrounds are removed automatically (stored as PNG). SVG and GIF are not altered.', max_length=500, upload_to='entity_page_logos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg'])], verbose_name='Organization logo'),
        ),
        migrations.AlterField(
            model_name='form',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when a super admin archives this form (soft delete). Archived forms are hidden from public and normal workspace lists.', null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='hide_from_form_lists',
            field=models.BooleanField(default=False, help_text='When on, this form is omitted from the organization public portal, the global home directory, and the workspace home form list (useful for related-only or parent-driven forms). Direct links, QR codes, submissions, and workspace form pages still work.', verbose_name='Hide from portal & home lists'),
        ),
    ]
