# Generated by Django 5.2.14 on 2026-09-20 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0093_field_options_2026_09'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='routing_mode',
            field=models.CharField(choices=[('fixed_steps', 'Fixed steps (configured order and assignees)'), ('dynamic', 'Dynamic routing (choose who receives it next, each time)')], default='fixed_steps', help_text='Fixed steps follow the ordered steps and assignees configured below. Dynamic routing lets whoever is acting choose the next person by name or job title instead of a pre-built path. Dynamic routing is being rolled out: forms set to it pause workflow actions until it is ready.', max_length=20, verbose_name='Workflow routing'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='current_holder',
            field=models.ForeignKey(blank=True, help_text='Dynamic routing only: who currently has this submission for action. Fixed-step forms use current_step and assigned_users instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='current_stage_label',
            field=models.CharField(blank=True, help_text='Dynamic routing only: free-text stage shown on the timeline and inbox, chosen at the last handoff.', max_length=255, verbose_name='Current stage'),
        ),
        migrations.AlterField(
            model_name='submissionevent',
            name='kind',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('step_changed', 'Workflow step changed'), ('note', 'Note'), ('step_approved', 'Step approved'), ('workflow_completed', 'Workflow completed'), ('approve_undone', 'Approval undone'), ('workflow_rejected', 'Workflow rejected'), ('routed', 'Routed to a person'), ('attachment_added', 'Document attached'), ('forwarded', 'Forwarded'), ('supplementary_invited', 'Related form available'), ('supplementary_submitted', 'Related form submitted')], max_length=32),
        ),
    ]
