# Generated by Django 5.2.14 on 2026-09-20 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0094_routing_mode_and_current_holder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='submit_route_role',
            field=models.CharField(blank=True, help_text="Dynamic routing only. When set, a new submission automatically goes to whoever holds this job title instead of opening to any organization member. Matched the same loose way as the “Route to” search (name or job title, partial match). Leave blank to keep today's behaviour.", max_length=255, verbose_name='Route new submissions to role'),
        ),
        migrations.AddField(
            model_name='form',
            name='submit_route_suggested_user',
            field=models.ForeignKey(blank=True, help_text="Learned automatically: the last person manually routed to for this form's submit-stage role, used as the default pick when more than one person currently holds that role.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submit_route_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form',
            name='routing_mode',
            field=models.CharField(choices=[('fixed_steps', 'Fixed steps (configured order and assignees)'), ('dynamic', 'Dynamic routing (choose who receives it next, each time)')], default='fixed_steps', help_text='Fixed steps follow the ordered steps and assignees configured below. Dynamic routing lets whoever is acting choose the next person by name or job title instead of a pre-built path.', max_length=20, verbose_name='Workflow routing'),
        ),
    ]
