# Generated by Django 5.2.14 on 2026-09-20 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicforms', '0095_form_submit_route_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='submit_route_suggested_user',
        ),
        migrations.CreateModel(
            name='FormSubmitRoutePick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_picked', models.PositiveIntegerField(default=0)),
                ('last_picked_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_route_picks', to='magicforms.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('form', 'user'), name='uniq_submit_route_pick_form_user')],
            },
        ),
    ]
